--Store confidential data of bots
CREATE TABLE IF NOT EXISTS TB_BOT_CREDENTIALS(
    BOT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DESCRIPTION VARCHAR(150),
    BOT_NAME VARCHAR(60) NOT NULL,
    EMAIL VARCHAR(120),
    LOGIN VARCHAR(120),
    PHONE_NUMBER VARCHAR(30), 
    PASSWORD VARCHAR(120) NOT NULL,
    UNIQUE(BOT_NAME)
);

-- Store Credentials to OPEN_VPN
CREATE TABLE IF NOT EXISTS TB_OPEN_VPN_CREDENTIALS (
    TB_OPEN_VPN_CREDENTIALS_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME VARCHAR(120) NOT NULL,
    PASSWORD VARCHAR(120) NOT NULL
);
