-- Find the initial data for bot 
SELECT B.BOT_ID, AU.ACTION_URL_ID, U.URL FROM TB_URL U 
    INNER JOIN TB_ACTION_URL AU ON U.URL_ID = AU.URL_ID 
    INNER JOIN TB_BOT_ACTION_URL BAU ON AU.ACTION_URL_ID = BAU.ACTION_URL_ID 
    INNER JOIN TB_BOT B ON B.BOT_ID = BAU.BOT_ID  
    INNER JOIN TB_ACTION A ON A.ACTION_ID = AU.ACTION_ID 
WHERE B.DESCRIPTION = ? AND A.DESCRIPTION = ?

-- Find the path of a file
SELECT PATH FROM TB_FILE_PATH 
WHERE BOT_ID = ( SELECT BOT_ID FROM TB_BOT WHERE DESCRIPTION = ? ) 

-- Find the xpath path 
SELECT X.XPATH, BAUX.DESCRIPTION FROM TB_XPATH X 
    INNER JOIN TB_BOT_ACTION_URL_XPATH BAUX ON X.XPATH_ID = BAUX.XPATH_ID 
    INNER JOIN TB_BOT_ACTION_URL BAU ON BAUX.BOT_ACTION_URL_ID = BAU.BOT_ACTION_URL_ID 
WHERE BAU.BOT_ID = ? AND BAU.ACTION_URL_ID = ? 

-- Find the xpath path with position
SELECT X.XPATH, BAUX.DESCRIPTION FROM TB_XPATH X 
    INNER JOIN TB_BOT_ACTION_URL_XPATH BAUX ON X.XPATH_ID = BAUX.XPATH_ID 
    INNER JOIN TB_BOT_ACTION_URL BAU ON BAUX.BOT_ACTION_URL_ID = BAU.BOT_ACTION_URL_ID 
WHERE BAU.BOT_ID = ? AND BAU.ACTION_URL_ID = ? 
    AND BAUX.POSITION = ? OR BAUX.POSITION IS NULL

-- Shows available bots
SELECT DESCRIPTION, BOT_NAME FROM TB_BOT_CREDENTIALS;
